(async()=>{
let state=await getState(),workspace='dashboard';
const LIB_KEY='descentContentLibraryV3_2',ACTIVE_KEY='descentActiveEncounterV3_2';
let cloudContentReady=false,cloudLibrary=[],cloudActive=null,cloudStatus='LOCAL FALLBACK';
const CONTENT_TABLE={item:'content_items',npc:'content_npcs',adversary:'content_adversaries',encounter:'content_encounters',quest:'content_quests',achievement:'content_achievements',loot_box:'content_loot_boxes',system_event:'system_events'};
const RAW_SLOTS=['Head','Torso','Arms','Hands/Holding','Legs','Feet','Accessories'];
const TIERS=['mundane','bronze','silver','gold','platinum','legendary','celestial'];
const POWER={2:{Weak:1,Moderate:2,Strong:3,Overwhelming:'4+'},3:{Weak:2,Moderate:3,Strong:5,Overwhelming:'6+'},4:{Weak:2,Moderate:4,Strong:6,Overwhelming:'8+'},5:{Weak:3,Moderate:5,Strong:8,Overwhelming:'10+'},6:{Weak:3,Moderate:6,Strong:9,Overwhelming:'12+'},7:{Weak:4,Moderate:7,Strong:11,Overwhelming:'14+'}};
const escA=esc;
function localLibrary(){try{return JSON.parse(localStorage.getItem(LIB_KEY)||'[]')}catch{return[]}}
function library(){return cloudContentReady?cloudLibrary:localLibrary()}
async function cloudUpsertContent(x){
 if(!cloudContentReady||!DSCloud.client)return;const table=CONTENT_TABLE[x.content_type];if(!table)return;
 const row={id:x.id,name:x.name||x.title||x.event_type||x.id,data:x,source_authority:x.source_authority||'THE_DESCENT'};
 if(x.content_type==='item')Object.assign(row,{category:x.category||'misc',gear_slot:x.gear_slot||null,tier:x.loot_tier||null,floor_min:x.floor_min||null});
 if(x.content_type==='npc')Object.assign(row,{npc_type:x.npc_type||null,floor_min:x.floor||null});
 if(x.content_type==='adversary')Object.assign(row,{classification:x.classification||null,floor_min:x.floor_min||null});
 if(x.content_type==='encounter')Object.assign(row,{floor_min:x.floor||null});
 if(x.content_type==='quest')Object.assign(row,{scope:x.scope||'Individual'});
 if(x.content_type==='achievement')Object.assign(row,{reward_tier:x.reward?.tier||null});
 if(x.content_type==='loot_box')Object.assign(row,{tier:x.tier||'bronze',box_type:x.box_type||null});
 if(x.content_type==='system_event')Object.assign(row,{event_type:x.event_type,status:x.status||'delivered',recipient_id:x.recipient_id||null,priority:x.priority||'normal',presentation:x.presentation||'popup',related_object_type:x.related_object_type||null,related_object_id:x.related_object_id||null});
 const {error}=await DSCloud.client.from(table).upsert(row);if(error)throw error;
}
function saveLibrary(x){
 localStorage.setItem(LIB_KEY,JSON.stringify(x));if(!cloudContentReady){cloudLibrary=x;return}
 const previous=library._last||[];cloudLibrary=x;const prevIds=new Set(previous.map(z=>z.id)),nowIds=new Set(x.map(z=>z.id));
 x.filter(z=>!prevIds.has(z.id)||JSON.stringify(previous.find(q=>q.id===z.id))!==JSON.stringify(z)).forEach(z=>cloudUpsertContent(z).catch(e=>console.error('Content upsert failed',e)));
 previous.filter(z=>!nowIds.has(z.id)).forEach(z=>{const t=CONTENT_TABLE[z.content_type];if(t)DSCloud.client.from(t).delete().eq('id',z.id).then(({error})=>{if(error)console.error(error)})});
 library._last=JSON.parse(JSON.stringify(x));
}
function active(){if(cloudContentReady)return cloudActive;try{return JSON.parse(localStorage.getItem(ACTIVE_KEY)||'null')}catch{return null}}
function saveActive(x){x?localStorage.setItem(ACTIVE_KEY,JSON.stringify(x)):localStorage.removeItem(ACTIVE_KEY);cloudActive=x;if(cloudContentReady&&DSCloud.client){if(x)DSCloud.client.from('active_encounters').upsert({id:x.instance_id,definition_id:x.definition_id||null,name:x.name,status:x.status||'active',round:x.round||1,phase:x.phase||'mobs',floor:x.floor||1,data:x}).then(({error})=>{if(error)console.error(error)});else DSCloud.client.from('active_encounters').delete().eq('status','active').then(({error})=>{if(error)console.error(error)})}}
async function initContentCloud(){
 if(!DSCloud.configured()||!DSCloud.client){cloudStatus='LOCAL FALLBACK';return}
 try{const all=[];for(const [type,table] of Object.entries(CONTENT_TABLE)){const {data,error}=await DSCloud.client.from(table).select('*').order('created_at',{ascending:true});if(error)throw error;(data||[]).forEach(r=>all.push(r.data||{...r,content_type:type}))}
 cloudLibrary=all;library._last=JSON.parse(JSON.stringify(all));const {data:a,error:ae}=await DSCloud.client.from('active_encounters').select('*').eq('status','active').order('created_at',{ascending:false}).limit(1);if(ae)throw ae;cloudActive=a?.[0]?.data||null;cloudContentReady=true;cloudStatus='SUPABASE CONTENT ENGINE';
 const local=localLibrary();if(!all.length&&local.length){for(const x of local)await cloudUpsertContent(x);cloudLibrary=local;library._last=JSON.parse(JSON.stringify(local))}localStorage.setItem(LIB_KEY,JSON.stringify(cloudLibrary));
 }catch(e){console.error('Content Engine cloud init failed',e);cloudContentReady=false;cloudStatus='LOCAL FALLBACK // RUN 3.3 MIGRATION'}}

function id(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,7)}
function crawler(cid){return state.crawlers.find(c=>String(c.id)===String(cid))}
function opts(selected=''){return state.crawlers.map(c=>`<option value="${escA(c.id)}" ${String(c.id)===String(selected)?'selected':''}>${escA(c.name)}</option>`).join('')}
function feed(text){addFeed(state,text);state=readState()||state}
function normalize(){for(const c of state.crawlers){c.quests=c.quests||[];c.achievements=c.achievements||[];c.lootBoxes=c.lootBoxes||[];c.messages=c.messages||[];if(c.pendingStatPoints==null)c.pendingStatPoints=0;if(c.healthSlotsRemaining==null)c.healthSlotsRemaining=10}}
function header(){
 normalize();const a=active(),lib=library();
 const levels=[...new Set(state.crawlers.map(c=>c.level))],floors=[...new Set(state.crawlers.map(c=>c.floor))];
 document.querySelector('#partySummary').textContent=`${state.crawlers.length} CRAWLERS // LV ${levels.join('/')} // FLOOR ${floors.join('/')}`;
 document.querySelector('#encounterSummary').textContent=a?`${a.name} // ROUND ${a.round} // ${a.phase.toUpperCase()}`:'NONE';
 document.querySelector('#librarySummary').textContent=`${lib.length} RECORD${lib.length===1?'':'S'}`;
 document.querySelector('#gmClock').textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' // '+cloudStatus;
}
function card(c){const cm=modFor(Number(c.stats?.CON||1));return `<article class="gm-crawler-card"><div><span class="tag">${escA(c.systemTitle||'CRAWLER')}</span><h3>${escA(c.name)}</h3></div><div class="gm-minihealth">${Array.from({length:10},(_,i)=>`<i class="${i<Number(c.healthSlotsRemaining||0)?'on':''}"></i>`).join('')}</div><div class="gm-cardstats"><span>HP ${Number(c.healthSlotsRemaining||0)*cm}/${cm*10}</span><span>LV ${c.level}</span><span>F${c.floor}</span><span>${c.pendingStatPoints||0} BANKED</span></div><div class="controls"><button data-hslot="${c.id}" data-d="-1">− SLOT</button><button data-hslot="${c.id}" data-d="1">+ SLOT</button><a class="btn" href="./character.html?id=${encodeURIComponent(c.id)}">OPEN HUD</a></div></article>`}
function dashboard(){
 const a=active();
 return `<section class="gm-dashboard"><div class="gm-party">${state.crawlers.map(card).join('')}</div>
 <aside class="gm-side"><div class="panel"><div class="tag">CONTENT ENGINE</div><h2>${escA(cloudStatus)}</h2><div class="muted small">${cloudContentReady?'Shared Supabase library is authoritative. Local storage is retained as a browser cache.':'Run the Phase 3.3 SQL migration, then reload. Existing local content remains available.'}</div>${cloudContentReady?'<button id="syncContentCloud">SYNC CONTENT NOW</button>':''}</div><div class="panel"><div class="tag">DUNGEON FEED</div><div class="feed">${(state.feed||[]).slice(0,18).map(x=>`<div class="feeditem"><b>${escA(x.at||'')}</b><br>${escA(x.text)}</div>`).join('')}</div></div>
 <div class="panel"><div class="tag">ENCOUNTER CONTROL</div>${a?`<h2>${escA(a.name)}</h2><div class="gm-encounter-readout"><b>ROUND ${a.round}</b><span>${escA(a.phase.toUpperCase())}</span></div>
 <div class="gm-combatants">${(a.participants||[]).filter(p=>p.kind==='adversary').map(p=>`<div class="gm-combatant"><div><b>${escA(p.name)}</b><span class="pill">DR ${p.dr||0}</span><span class="pill">EVADE ${escA(p.evade||'—')}</span></div><div class="gm-minihealth">${Array.from({length:p.health.slots_max},(_,i)=>`<i class="${i<p.health.slots_current?'on':''}"></i>`).join('')}</div><div class="small muted">${p.health.slots_current}/${p.health.slots_max} HEALTH SLOTS${(p.conditions||[]).length?' // '+escA(p.conditions.join(', ')):''}</div><div class="controls"><button data-mobslot="${p.participant_id}" data-d="-1">− SLOT</button><button data-mobslot="${p.participant_id}" data-d="1">+ SLOT</button><select data-atkselect="${p.participant_id}">${(p.attacks||[]).map((a,i)=>`<option value="${i}">${escA(a.name)}</option>`).join('')}</select><button data-mobattack="${p.participant_id}">ATTACK</button><button data-condition="${p.participant_id}">CONDITION</button></div></div>`).join('')||'<p class="muted">No adversaries instantiated.</p>'}</div>
 ${a.phase==='crawlers'?`<div class="gm-actions-board">${state.crawlers.map(c=>`<div><b>${escA(c.name)}</b><span>${Number(a.actions_remaining?.[c.id]??2)} ACTIONS</span><button data-spendaction="${c.id}">SPEND</button><button data-resetaction="${c.id}">RESET</button></div>`).join('')}</div>`:''}
 <div class="controls"><button id="nextPhase" class="primary">NEXT PHASE</button><button id="resetRoundActions">RESET ACTIONS</button><button id="endEncounter" class="danger">RESOLVE</button></div>`:`<h2>NO ACTIVE ENCOUNTER</h2><p class="muted">Stage an encounter from the Encounter workspace.</p><button data-jump="encounters" class="primary">OPEN ENCOUNTERS</button>`}</div></aside></section>`;
}
function actions(){
 return `<section class="gm-two">
 <div class="panel"><div class="tag">SYSTEM EVENT</div><h2>GM Actions</h2><div class="field"><label>Crawler</label><select id="actionWho">${opts()}</select></div><div class="field"><label>Event Type</label><select id="actionType"><option>Private System Message</option><option>Achievement</option><option>Quest</option><option>GM Notes</option><option>System Announcement</option></select></div><div class="field"><label>Title / Name</label><input id="actionTitle"></div><div class="field"><label>Message / Details</label><textarea id="actionBody" rows="7"></textarea></div><button id="deployAction" class="primary">DEPLOY EVENT</button></div>
 <div class="panel"><div class="tag">PARTY PROGRESSION</div><h2>RAW Tutorial Controls</h2><div class="notice">Level gain banks 3 Stat Points per crawler. Tutorial Floor points remain banked until Floor 3.</div><div class="row"><div><b>Party Level</b><div class="muted small">+1 Level // +3 banked Stat Points</div></div><button id="partyLevelUp" class="primary">PARTY +1 LEVEL</button></div><div class="row"><div><b>Party Floor</b><div class="muted small">Advance all crawlers one Floor.</div></div><button id="partyFloorUp" class="primary">PARTY +1 FLOOR</button></div><hr><div class="tag">QUICK LOOT BOX</div><div class="field"><label>Crawler</label><select id="lootWho">${opts()}</select></div><div class="field"><label>Tier</label><select id="lootTier">${TIERS.slice(1).map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label>Name</label><input id="lootName" placeholder="Bronze Adventurer Box"></div><div class="field"><label>Contents / GM notes</label><textarea id="lootContents" rows="4"></textarea></div><button id="stageLoot">STAGE SEALED BOX</button></div></section>`;
}
function rewards(){
 const lib=library(),qs=lib.filter(x=>x.content_type==='quest'),as=lib.filter(x=>x.content_type==='achievement'),ls=lib.filter(x=>x.content_type==='loot_box'),events=lib.filter(x=>x.content_type==='system_event');
 return `<section class="gm-rewards">
 <div class="gm-rewardtabs">
 <div class="panel"><span class="tag">QUEST WORKSHOP</span><h2>Quest Definition</h2><div class="field"><label>Name</label><input id="rwQuestName"></div><div class="field"><label>Scope</label><select id="rwQuestScope"><option>Individual</option><option>Group</option></select></div><div class="field"><label>Description</label><textarea id="rwQuestDesc" rows="3"></textarea></div><div class="field"><label>Objectives — one per line</label><textarea id="rwQuestObj" rows="4"></textarea></div><div class="field"><label>Completion / Reward Notes</label><textarea id="rwQuestReward" rows="3"></textarea></div><button id="saveQuestDef" class="primary">SAVE QUEST</button></div>
 <div class="panel"><span class="tag">ACHIEVEMENT WORKSHOP</span><h2>Achievement Definition</h2><div class="field"><label>Name</label><input id="rwAchName"></div><div class="field"><label>Description / System Quip</label><textarea id="rwAchDesc" rows="4"></textarea></div><div class="field"><label>Reward Box</label><select id="rwAchBox"><option value="">No tangible reward</option>${TIERS.slice(1).map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label>Box Name</label><input id="rwAchBoxName" placeholder="Adventurer's Box"></div><div class="field"><label>GM-only Contents</label><textarea id="rwAchContents" rows="3"></textarea></div><button id="saveAchievementDef" class="primary">SAVE ACHIEVEMENT</button></div>
 <div class="panel"><span class="tag">LOOT BOX WORKSHOP</span><h2>Loot Box Definition</h2><div class="field"><label>Name</label><input id="rwBoxName"></div><div class="field"><label>Tier</label><select id="rwBoxTier">${TIERS.slice(1).map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label>Box Type</label><input id="rwBoxType" value="Adventurer"></div><div class="field"><label>Contents / GM Notes</label><textarea id="rwBoxContents" rows="4"></textarea></div><button id="saveBoxDef" class="primary">SAVE LOOT BOX</button></div>
 </div>
 <div class="panel"><div class="gm-library-head"><div><span class="tag">QUEST / REWARD LIBRARY</span><h2>${qs.length+as.length+ls.length} Definitions</h2></div><select id="rewardFilter"><option value="all">ALL</option><option value="quest">QUESTS</option><option value="achievement">ACHIEVEMENTS</option><option value="loot_box">LOOT BOXES</option></select></div>
 <div id="rewardList">${[...qs,...as,...ls].map(x=>`<div class="gm-library-row" data-rwtype="${x.content_type}"><div><b>${escA(x.name)}</b><div class="muted small">${escA(x.content_type.toUpperCase().replace('_',' '))} // ${escA(x.source_authority||'THE_DESCENT')}</div><div class="muted">${escA(x.description||x.contents||'')}</div></div><div class="controls"><button data-deployreward="${x.id}" class="primary">DEPLOY</button><button data-deletecontent="${x.id}" class="danger">DELETE</button></div></div>`).join('')||'<p class="muted">No Quest/Reward definitions yet.</p>'}</div></div>
 <div class="panel"><span class="tag">SYSTEM EVENT QUEUE</span><h2>${events.length} Recorded Events</h2><div class="gm-eventqueue">${events.slice().reverse().slice(0,25).map(e=>`<div class="feeditem"><b>${escA(e.event_type)} // ${escA(e.status)}</b><br>${escA(e.title||'')}${e.recipient_name?' → '+escA(e.recipient_name):''}<div class="muted small">${escA(e.created_at||'')}</div></div>`).join('')||'<p class="muted">No structured System events yet.</p>'}</div></div>
 </section>`;
}
function queueEvent(evt){
 const lib=library();const e={schema_version:'1.0',content_type:'system_event',id:id('event'),event_type:evt.event_type||'notification',title:evt.title||'',body:evt.body||'',recipient_id:evt.recipient_id||null,recipient_name:evt.recipient_name||null,priority:evt.priority||'normal',presentation:evt.presentation||'popup',acknowledgement_required:evt.acknowledgement_required!==false,status:evt.status||'queued',related_object_type:evt.related_object_type||null,related_object_id:evt.related_object_id||null,created_at:new Date().toISOString(),source_authority:evt.source_authority||'THE_DESCENT'};lib.push(e);saveLibrary(lib);return e;
}
async function deployRewardDefinition(x){
 const who=prompt('Deploy to crawler ID, exact crawler name, or PARTY:',state.crawlers[0]?.name||'');if(who===null)return;
 const targets=String(who).trim().toUpperCase()==='PARTY'?state.crawlers:state.crawlers.filter(z=>String(z.id).toLowerCase()===String(who).toLowerCase()||String(z.name).toLowerCase()===String(who).toLowerCase());
 if(!targets.length)return alert('Crawler not found.');
 for(const c of targets){
  if(x.content_type==='quest'){c.quests=c.quests||[];c.quests.push({id:id('questinst'),definition_id:x.id,name:x.name,detail:x.description,status:'ACTIVE',objectives:(x.objectives||[]).map(o=>({...o,status:'ACTIVE'})),reward:x.reward_notes||''});await saveCrawlerNow(c);await sendPrivateSystemMessage(c.id,`NEW QUEST! // ${x.name}\n${x.description||''}`);queueEvent({event_type:'quest_received',title:x.name,body:x.description,recipient_id:c.id,recipient_name:c.name,related_object_type:'quest',related_object_id:x.id});}
  if(x.content_type==='achievement'){c.achievements=c.achievements||[];c.achievements.push({id:id('achinst'),definition_id:x.id,name:x.name,reward:x.reward?.box_name||x.reward?.tier||'No tangible reward',description:x.description,claimStatus:'UNCLAIMED'});if(x.reward?.tier){c.lootBoxes=c.lootBoxes||[];c.lootBoxes.push({id:id('loot'),definition_id:x.reward.loot_box_definition_id||null,name:x.reward.box_name||`${x.reward.tier} Loot Box`,tier:x.reward.tier,contents:x.contents||'',opened:false,awardedAt:new Date().toISOString()});}await saveCrawlerNow(c);await sendPrivateSystemMessage(c.id,`NEW ACHIEVEMENT! // ${x.name}\n${x.description||''}${x.reward?.tier?`\nREWARD: ${x.reward.tier.toUpperCase()} ${x.reward.box_name||'LOOT BOX'}`:''}`);queueEvent({event_type:'achievement',title:x.name,body:x.description,recipient_id:c.id,recipient_name:c.name,priority:'high',presentation:'popup',related_object_type:'achievement',related_object_id:x.id});}
  if(x.content_type==='loot_box'){c.lootBoxes=c.lootBoxes||[];c.lootBoxes.push({id:id('loot'),definition_id:x.id,name:x.name,tier:x.tier,contents:x.contents||'',opened:false,awardedAt:new Date().toISOString()});await saveCrawlerNow(c);await sendPrivateSystemMessage(c.id,`LOOT BOX RECEIVED // ${x.tier.toUpperCase()} ${x.name}`);queueEvent({event_type:'loot_box_received',title:x.name,recipient_id:c.id,recipient_name:c.name,priority:'high',presentation:'popup',related_object_type:'loot_box',related_object_id:x.id});}
 }
 feed(`${x.name} deployed to ${targets.length===state.crawlers.length?'the party':targets.map(c=>c.name).join(', ')}.`);state=readState()||state;render();
}
function items(){
 const lib=library(),items=lib.filter(x=>x.content_type==='item');
 return `<section class="gm-library-layout"><div class="panel"><div class="tag">CONTENT WORKSHOP</div><h2>Item Definition</h2><div class="gm-formgrid">
 <div class="field"><label>Name</label><input id="itemName"></div><div class="field"><label>Category</label><select id="itemCategory">${['gear','weapon','consumable','scroll','spellbook','quest_item','crafting','container','tool','misc'].map(x=>`<option>${x}</option>`).join('')}</select></div>
 <div class="field"><label>Gear Slot</label><select id="itemSlot"><option value="">None</option>${RAW_SLOTS.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Loot Tier</label><select id="itemTier">${TIERS.map(x=>`<option>${x}</option>`).join('')}</select></div>
 <div class="field"><label>Source Authority</label><select id="itemSource"><option>THE_DESCENT</option><option>RAW_CORE</option><option>RAW_TOOLKIT</option><option>GM_CREATED</option><option>AI_GENERATED</option><option>HOMEBREW</option></select></div><div class="field"><label>Floor Minimum</label><input id="itemFloor" type="number" min="1" value="1"></div>
 <div class="field wide"><label>System Description</label><textarea id="itemDesc" rows="3"></textarea></div><div class="field wide"><label>Mechanical Effect</label><textarea id="itemEffect" rows="3" placeholder="Structured automation comes next; record the verified effect here."></textarea></div></div>
 <div class="controls"><button id="saveItem" class="primary">SAVE TO LIBRARY</button><button id="clearItem">CLEAR</button></div></div>
 <div class="panel"><div class="gm-library-head"><div><span class="tag">ITEM LIBRARY</span><h2>${items.length} Definitions</h2></div><input id="itemSearch" placeholder="Search items..."></div><div id="itemList">${renderItemList(items)}</div></div></section>`;
}
function renderItemList(items){return items.length?items.map(x=>`<div class="gm-library-row" data-search="${escA((x.name+' '+x.category+' '+(x.gear_slot||'')+' '+x.loot_tier).toLowerCase())}"><div><b>${escA(x.name)}</b><div class="muted small">${escA(x.category.toUpperCase())} // ${escA(x.gear_slot||'NOT EQUIPPABLE')} // ${escA((x.loot_tier||'mundane').toUpperCase())}</div><div class="muted">${escA(x.system_description||'')}</div></div><div class="controls"><span class="pill">${escA(x.source_authority)}</span><button data-awarditem="${x.id}">AWARD</button><button data-deletecontent="${x.id}" class="danger">DELETE</button></div></div>`).join(''):'<p class="muted">No item definitions yet.</p>'}
function npcs(){
 const lib=library(),npcs=lib.filter(x=>x.content_type==='npc');
 return `<section class="gm-library-layout"><div class="panel"><div class="tag">NPC WORKSHOP</div><h2>NPC Definition</h2><div class="gm-formgrid"><div class="field"><label>Name</label><input id="npcName"></div><div class="field"><label>Type</label><select id="npcType">${['Game Guide','Vendor','Quest NPC','Public Relations Agent','Interview/Media','Civilian','Authority','Rival Crawler','Other'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Floor</label><input id="npcFloor" type="number" min="1" value="1"></div><div class="field"><label>Status</label><select id="npcStatus"><option>active</option><option>friendly</option><option>neutral</option><option>hostile</option><option>missing</option><option>dead</option><option>inactive</option></select></div><div class="field"><label>Location</label><input id="npcLocation"></div><div class="field"><label>Faction</label><input id="npcFaction"></div><div class="field wide"><label>Personality / Behavior</label><textarea id="npcPersonality" rows="4"></textarea></div><div class="field wide"><label>GM Secrets / Restrictions</label><textarea id="npcSecrets" rows="4"></textarea></div></div><button id="saveNpc" class="primary">SAVE NPC</button></div>
 <div class="panel"><span class="tag">NPC DIRECTORY</span><h2>${npcs.length} Records</h2>${npcs.length?npcs.map(x=>`<div class="gm-library-row"><div><b>${escA(x.name)}</b><div class="muted small">${escA(x.npc_type)} // FLOOR ${x.floor||'—'} // ${escA(x.status)}</div><div class="muted">${escA(x.location||'Location not set')}</div></div><div class="controls"><span class="pill">${escA(x.source_authority)}</span><button data-deletecontent="${x.id}" class="danger">DELETE</button></div></div>`).join(''):'<p class="muted">No NPC records yet.</p>'}</div></section>`;
}
function adversaries(){
 const lib=library(),ads=lib.filter(x=>x.content_type==='adversary');
 return `<section class="gm-library-layout"><div class="panel"><div class="tag">ADVERSARY WORKSHOP</div><h2>RAW Combat Profile</h2>
 <div class="gm-formgrid">
 <div class="field"><label>Name</label><input id="advName"></div><div class="field"><label>Classification</label><select id="advClass">${['Mob','Neighborhood Boss','Borough Boss','City Boss','Crawler','NPC','Other'].map(x=>`<option>${x}</option>`).join('')}</select></div>
 <div class="field"><label>Species / Type</label><input id="advSpecies"></div><div class="field"><label>Size</label><input id="advSize" value="Medium"></div>
 <div class="field"><label>Level</label><input id="advLevel" type="number" min="1" value="1"></div><div class="field"><label>Health Slots</label><input id="advHealth" type="number" min="1" value="10"></div>
 <div class="field"><label>Surprise</label><input id="advSurprise" value="11+F"></div><div class="field"><label>Evade</label><input id="advEvade" value="11+F"></div>
 <div class="field"><label>Move</label><input id="advMove" value="20+S"></div><div class="field"><label>DR</label><input id="advDR" type="number" min="0" value="1"></div>
 ${['STR','INT','CON','DEX','CHA'].map(s=>`<div class="field"><label>${s}</label><input id="adv${s}" type="number" min="1" value="3"></div>`).join('')}
 <div class="field"><label>Source Authority</label><select id="advSource"><option>THE_DESCENT</option><option>RAW_CORE</option><option>RAW_TOOLKIT</option><option>GM_CREATED</option><option>AI_GENERATED</option><option>HOMEBREW</option></select></div>
 </div><hr><div class="tag">PRIMARY ATTACK</div><div class="gm-formgrid">
 <div class="field"><label>Attack Name</label><input id="advAtkName" value="Attack"></div><div class="field"><label>To-Hit Difficulty</label><input id="advAtkHit" value="11+F"></div>
 <div class="field"><label>Damage</label><input id="advAtkDamage" value="1D6"></div><div class="field"><label>Damage Type</label><input id="advAtkType" value="Physical"></div>
 <div class="field"><label>Range</label><input id="advAtkRange" value="Melee"></div><div class="field"><label>On Hit / Fail Effect</label><input id="advAtkEffect"></div>
 <div class="field wide"><label>Special Rules / Notes</label><textarea id="advNotes" rows="5"></textarea></div><div class="field wide"><label>System / AI Announcement</label><textarea id="advAnnouncement" rows="3"></textarea></div>
 </div><button id="saveAdversary" class="primary">SAVE ADVERSARY</button></div>
 <div class="panel"><div class="gm-library-head"><div><span class="tag">ADVERSARY LIBRARY</span><h2>${ads.length} Profiles</h2></div><input id="advSearch" placeholder="Search adversaries..."></div><div id="advList">${renderAdversaries(ads)}</div></div></section>`;
}
function renderAdversaries(ads){return ads.length?ads.map(x=>`<div class="gm-library-row" data-search="${escA((x.name+' '+x.classification+' '+(x.species_type||'')).toLowerCase())}"><div><b>${escA(x.name)}</b><div class="muted small">${escA(x.classification.toUpperCase())} // LV ${x.level} // ${escA(x.size?.name||'—')} // DR ${x.dr} // EVADE ${escA(x.evade)}</div><div class="muted">${escA(x.attacks?.[0]?.name||'No attack')} // ${escA(x.attacks?.[0]?.damage||'—')} ${escA(x.attacks?.[0]?.damage_type||'')}</div></div><div class="controls"><span class="pill">${escA(x.source_authority)}</span><button data-addadv="${x.id}">ADD TO ENCOUNTER</button><button data-deletecontent="${x.id}" class="danger">DELETE</button></div></div>`).join(''):'<p class="muted">No adversary profiles yet.</p>'}
function encounters(){
 const lib=library(),encs=lib.filter(x=>x.content_type==='encounter'),a=active();
 return `<section class="gm-library-layout"><div class="panel"><div class="tag">ENCOUNTER WORKSHOP</div><h2>Encounter Definition</h2><div class="gm-formgrid"><div class="field"><label>Name</label><input id="encName"></div><div class="field"><label>Type</label><select id="encType">${['combat','boss','trap','social','exploration','chase','mixed'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Floor</label><input id="encFloor" type="number" min="1" value="${state.crawlers[0]?.floor||1}"></div><div class="field"><label>Power Band</label><select id="encPower"><option>Weak</option><option selected>Moderate</option><option>Strong</option><option>Overwhelming</option></select></div><div class="field"><label>Party Size</label><input id="encParty" type="number" min="2" max="7" value="${Math.min(7,Math.max(2,state.crawlers.length))}"></div><div class="field"><label>Adversary Count</label><input id="encCount" type="number" min="0" value="${Math.min(7,Math.max(2,state.crawlers.length))}"></div>
 <div class="field wide"><label>Saved Adversary</label><select id="encSavedAdv"><option value="">— Use inline template below —</option>${library().filter(x=>x.content_type==='adversary').map(x=>`<option value="${x.id}">${escA(x.name)} // ${escA(x.classification)}</option>`).join('')}</select></div>
 <div class="field"><label>Adversary Name</label><input id="encMobName" value="Dungeon Mob"></div><div class="field"><label>Health Bar Slots</label><input id="encMobHealth" type="number" min="1" value="10"></div>
 <div class="field"><label>Evade</label><input id="encMobEvade" value="11+F"></div><div class="field"><label>DR</label><input id="encMobDr" type="number" min="0" value="1"></div>
 <div class="field"><label>Attack</label><input id="encMobAttack" value="Attack"></div><div class="field"><label>Damage</label><input id="encMobDamage" value="1D6"></div>
 <div class="field wide"><label>System Announcement</label><textarea id="encAnnouncement" rows="3"></textarea></div><div class="field wide"><label>Objectives</label><textarea id="encObjectives" rows="3" placeholder="One objective per line"></textarea></div><div class="field wide"><label>GM Notes / Special Rules</label><textarea id="encNotes" rows="4"></textarea></div></div><div id="powerHint" class="notice"></div><button id="saveEncounter" class="primary">SAVE ENCOUNTER</button></div>
 <div class="panel"><span class="tag">ENCOUNTER LIBRARY</span><h2>${encs.length} Definitions</h2>${a?`<div class="notice"><b>ACTIVE:</b> ${escA(a.name)} // ROUND ${a.round} // ${escA(a.phase.toUpperCase())}</div>`:''}${encs.length?encs.map(x=>`<div class="gm-library-row"><div><b>${escA(x.name)}</b><div class="muted small">${escA(x.encounter_type.toUpperCase())} // FLOOR ${x.floor} // ${escA(x.power_band||'')}</div><div class="muted">${escA(x.system_announcement||'')}</div></div><div class="controls"><button data-deployenc="${x.id}" class="primary">DEPLOY</button><button data-deletecontent="${x.id}" class="danger">DELETE</button></div></div>`).join(''):'<p class="muted">No encounter definitions yet.</p>'}</div></section>`;
}
function tables(){
 return `<section class="gm-two"><div class="panel"><span class="tag">RAW REFERENCE</span><h2>Adversary Power</h2><div class="gm-tablewrap"><table><thead><tr><th>Party</th><th>Weak</th><th>Moderate</th><th>Strong</th><th>Overwhelming</th></tr></thead><tbody>${Object.entries(POWER).map(([p,v])=>`<tr><td>${p}</td><td>${v.Weak}</td><td>${v.Moderate}</td><td>${v.Strong}</td><td>${v.Overwhelming}</td></tr>`).join('')}</tbody></table></div><p class="muted small">RAW starting point only. GM adjustment remains authoritative.</p></div><div class="panel"><span class="tag">DICE TABLE</span><h2>Quick Roller</h2><div class="controls">${[4,6,8,10,12,20,100].map(d=>`<button data-die="${d}">d${d}</button>`).join('')}</div><div class="gm-roll" id="tableRoll">—</div><div class="notice">Custom campaign tables will become saved Content Engine records in the next iteration.</div></div></section>`;
}
function render(){
 header();document.querySelectorAll('[data-workspace]').forEach(b=>b.classList.toggle('active',b.dataset.workspace===workspace));
 const w=document.querySelector('#workspace');w.innerHTML=workspace==='dashboard'?dashboard():workspace==='actions'?actions():workspace==='rewards'?rewards():workspace==='items'?items():workspace==='npcs'?npcs():workspace==='adversaries'?adversaries():workspace==='encounters'?encounters():tables();
 bind();
}
async function saveC(c,msg){await saveCrawlerNow(c);if(msg)feed(msg);state=readState()||state;render()}
function bind(){
 document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{workspace=b.dataset.jump;render()});
 document.querySelector('#syncContentCloud')?.addEventListener('click',async()=>{try{for(const x of library())await cloudUpsertContent(x);alert('Content Engine sync complete.')}catch(e){alert('Sync failed: '+e.message)}});
 document.querySelectorAll('[data-hslot]').forEach(b=>b.onclick=async()=>{const c=crawler(b.dataset.hslot);c.healthSlotsRemaining=Math.max(0,Math.min(10,Number(c.healthSlotsRemaining||0)+Number(b.dataset.d)));await saveC(c,`${c.name} Health Bar adjusted to ${c.healthSlotsRemaining}/10 slots by GM.`)});
 document.querySelector('#nextPhase')?.addEventListener('click',()=>{const a=active();if(!a)return;if(a.phase==='mobs')a.phase='crawlers';else{a.phase='mobs';a.round++;a.actions_remaining=Object.fromEntries(state.crawlers.map(c=>[c.id,2]))}saveActive(a);feed(`Encounter ${a.name} advanced to Round ${a.round}, ${a.phase} phase.`);render()});
 document.querySelectorAll('[data-mobslot]').forEach(b=>b.onclick=()=>{const a=active(),p=(a.participants||[]).find(x=>x.participant_id===b.dataset.mobslot);if(!p)return;p.health.slots_current=Math.max(0,Math.min(p.health.slots_max,Number(p.health.slots_current||0)+Number(b.dataset.d)));a.event_log.push({at:new Date().toISOString(),text:`${p.name} Health Bar: ${p.health.slots_current}/${p.health.slots_max}`});saveActive(a);render()});
 document.querySelectorAll('[data-condition]').forEach(b=>b.onclick=()=>{const a=active(),p=(a.participants||[]).find(x=>x.participant_id===b.dataset.condition);if(!p)return;const v=prompt(`Conditions for ${p.name} (comma separated):`,(p.conditions||[]).join(', '));if(v===null)return;p.conditions=v.split(',').map(x=>x.trim()).filter(Boolean);saveActive(a);render()});
 document.querySelectorAll('[data-mobattack]').forEach(b=>b.onclick=()=>{const a=active(),p=(a.participants||[]).find(x=>x.participant_id===b.dataset.mobattack);if(!p)return;const sel=document.querySelector(`[data-atkselect="${p.participant_id}"]`),atk=(p.attacks||[])[Number(sel?.value||0)]||{name:'Attack',to_hit:'—',damage:'—'},d20=rollDie(20);a.event_log.push({at:new Date().toISOString(),text:`${p.name} used ${atk.name}: d20 ${d20}; to-hit ${atk.to_hit||'—'}; damage ${atk.damage}.`});saveActive(a);feed(`${p.name} // ${atk.name}: d20 ${d20} // To-Hit ${atk.to_hit||'—'} // Damage ${atk.damage}.`);alert(`${p.name} — ${atk.name}\nD20: ${d20}\nTo-Hit: ${atk.to_hit||'—'}\nDamage: ${atk.damage} ${atk.damage_type||''}\nRange: ${atk.range||'—'}${atk.other_effects?.length?'\nEffect: '+atk.other_effects.map(x=>x.text||JSON.stringify(x)).join('; '):''}`);render()});
 document.querySelectorAll('[data-spendaction]').forEach(b=>b.onclick=()=>{const a=active(),cid=b.dataset.spendaction;a.actions_remaining=a.actions_remaining||{};a.actions_remaining[cid]=Math.max(0,Number(a.actions_remaining[cid]??2)-1);saveActive(a);render()});
 document.querySelectorAll('[data-resetaction]').forEach(b=>b.onclick=()=>{const a=active();a.actions_remaining=a.actions_remaining||{};a.actions_remaining[b.dataset.resetaction]=2;saveActive(a);render()});
 document.querySelector('#resetRoundActions')?.addEventListener('click',()=>{const a=active();a.actions_remaining=Object.fromEntries(state.crawlers.map(c=>[c.id,2]));saveActive(a);render()});
 document.querySelector('#endEncounter')?.addEventListener('click',()=>{const a=active();if(a&&confirm(`Resolve ${a.name}?`)){feed(`Encounter resolved: ${a.name}.`);saveActive(null);render()}});
 document.querySelector('#deployAction')?.addEventListener('click',async()=>{const c=crawler(document.querySelector('#actionWho').value),type=document.querySelector('#actionType').value,title=document.querySelector('#actionTitle').value.trim(),body=document.querySelector('#actionBody').value.trim();if(!body&&!title)return alert('Enter event content.');if(type==='Private System Message'){await sendPrivateSystemMessage(c.id,body||title);queueEvent({event_type:'private_message',title:'SYSTEM MESSAGE',body:body||title,recipient_id:c.id,recipient_name:c.name});feed(`${c.name} received a private System message.`)}else if(type==='Achievement'){c.achievements.push({name:title||'Achievement',reward:body,claimStatus:'UNCLAIMED'});queueEvent({event_type:'achievement',title:title||'Achievement',body,recipient_id:c.id,recipient_name:c.name,priority:'high'});await saveC(c,`${c.name} received achievement: ${title||'Achievement'}.`);return}else if(type==='Quest'){c.quests.push({name:title||'Quest',detail:body,status:'ACTIVE'});queueEvent({event_type:'quest_received',title:title||'Quest',body,recipient_id:c.id,recipient_name:c.name});await saveC(c,`${c.name} received quest: ${title||'Quest'}.`);return}else if(type==='GM Notes'){c.notes=body;await saveC(c,`${c.name} GM Notes updated.`);return}else{for(const x of state.crawlers){await sendPrivateSystemMessage(x.id,`SYSTEM ANNOUNCEMENT${title?' // '+title:''}\n${body}`);queueEvent({event_type:'system_announcement',title:title||'SYSTEM ANNOUNCEMENT',body,recipient_id:x.id,recipient_name:x.name,priority:'high',presentation:'banner'});}feed(`System announcement deployed to the party: ${title||body.slice(0,40)}.`)}state=readState()||state;render()});
 document.querySelector('#partyLevelUp')?.addEventListener('click',async()=>{if(!confirm('Advance every crawler +1 Level and bank +3 Stat Points?'))return;for(const c of state.crawlers){c.level=Number(c.level||1)+1;c.pendingStatPoints=Number(c.pendingStatPoints||0)+3;await saveCrawlerNow(c)}feed('Party advanced +1 Level. Each crawler banked 3 Stat Points.');state=readState()||state;render()});
 document.querySelector('#partyFloorUp')?.addEventListener('click',async()=>{if(!confirm('Advance every crawler +1 Floor?'))return;for(const c of state.crawlers){c.floor=Number(c.floor||1)+1;await saveCrawlerNow(c)}feed('Party advanced +1 Floor.');state=readState()||state;render()});
 document.querySelector('#stageLoot')?.addEventListener('click',async()=>{const c=crawler(document.querySelector('#lootWho').value),tier=document.querySelector('#lootTier').value,name=document.querySelector('#lootName').value.trim(),contents=document.querySelector('#lootContents').value.trim();if(!name)return alert('Enter a loot box name.');c.lootBoxes.push({id:id('loot'),name,tier,contents,opened:false,awardedAt:new Date().toISOString()});await saveC(c,`${c.name} received sealed ${tier} loot box: ${name}.`)});
 document.querySelector('#saveQuestDef')?.addEventListener('click',()=>{const name=document.querySelector('#rwQuestName').value.trim();if(!name)return alert('Quest name required.');const x={schema_version:'1.0',content_type:'quest',id:id('quest'),name,scope:document.querySelector('#rwQuestScope').value,description:document.querySelector('#rwQuestDesc').value.trim(),objectives:document.querySelector('#rwQuestObj').value.split('\n').map(x=>x.trim()).filter(Boolean).map((text,i)=>({id:'obj_'+(i+1),text,required:true})),reward_notes:document.querySelector('#rwQuestReward').value.trim(),source_authority:'THE_DESCENT',gm_approval_required:false};const lib=library();lib.push(x);saveLibrary(lib);queueEvent({event_type:'content_created',title:name,body:'Quest Definition saved.',related_object_type:'quest',related_object_id:x.id,status:'recorded'});render()});
 document.querySelector('#saveAchievementDef')?.addEventListener('click',()=>{const name=document.querySelector('#rwAchName').value.trim();if(!name)return alert('Achievement name required.');const tier=document.querySelector('#rwAchBox').value;const x={schema_version:'1.0',content_type:'achievement',id:id('achievement'),name,description:document.querySelector('#rwAchDesc').value.trim(),reward:tier?{tier,box_name:document.querySelector('#rwAchBoxName').value.trim()||`${tier} Loot Box`}:null,contents:document.querySelector('#rwAchContents').value.trim(),source_authority:'THE_DESCENT',gm_approval_required:false};const lib=library();lib.push(x);saveLibrary(lib);queueEvent({event_type:'content_created',title:name,body:'Achievement Definition saved.',related_object_type:'achievement',related_object_id:x.id,status:'recorded'});render()});
 document.querySelector('#saveBoxDef')?.addEventListener('click',()=>{const name=document.querySelector('#rwBoxName').value.trim();if(!name)return alert('Loot Box name required.');const x={schema_version:'1.0',content_type:'loot_box',id:id('lootboxdef'),name,tier:document.querySelector('#rwBoxTier').value,box_type:document.querySelector('#rwBoxType').value.trim()||'Adventurer',contents:document.querySelector('#rwBoxContents').value.trim(),source_authority:'THE_DESCENT',gm_approval_required:false};const lib=library();lib.push(x);saveLibrary(lib);queueEvent({event_type:'content_created',title:name,body:'Loot Box Definition saved.',related_object_type:'loot_box',related_object_id:x.id,status:'recorded'});render()});
 document.querySelector('#rewardFilter')?.addEventListener('change',e=>document.querySelectorAll('#rewardList [data-rwtype]').forEach(r=>r.classList.toggle('hidden',e.target.value!=='all'&&r.dataset.rwtype!==e.target.value)));
 document.querySelectorAll('[data-deployreward]').forEach(b=>b.onclick=()=>{const x=library().find(z=>z.id===b.dataset.deployreward);if(x)deployRewardDefinition(x)});
 document.querySelector('#saveItem')?.addEventListener('click',()=>{const name=document.querySelector('#itemName').value.trim();if(!name)return alert('Item name required.');const x={schema_version:'1.0',content_type:'item',id:id('item'),name,category:document.querySelector('#itemCategory').value,gear_slot:document.querySelector('#itemSlot').value||null,loot_tier:document.querySelector('#itemTier').value,floor_min:Number(document.querySelector('#itemFloor').value||1),source_authority:document.querySelector('#itemSource').value,system_description:document.querySelector('#itemDesc').value.trim(),mechanics:{notes:document.querySelector('#itemEffect').value.trim()},gm_approval_required:['AI_GENERATED','HOMEBREW'].includes(document.querySelector('#itemSource').value)};const lib=library();lib.push(x);saveLibrary(lib);feed(`Content Library saved item: ${name}.`);render()});
 document.querySelector('#itemSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#itemList [data-search]').forEach(r=>r.classList.toggle('hidden',!r.dataset.search.includes(q)))});
 document.querySelectorAll('[data-awarditem]').forEach(b=>b.onclick=async()=>{const x=library().find(z=>z.id===b.dataset.awarditem);if(!x)return;const who=prompt('Award to crawler ID or exact crawler name:',state.crawlers[0]?.name||'');const c=state.crawlers.find(z=>String(z.id).toLowerCase()===String(who).toLowerCase()||String(z.name).toLowerCase()===String(who).toLowerCase());if(!c)return alert('Crawler not found.');c.inventory=c.inventory||[];c.inventory.push({id:id('owned'),definition_id:x.id,name:x.name,category:x.category==='gear'||x.category==='weapon'?'Equipment':x.category==='consumable'?'Consumable':'Other',type:x.category,gearSlot:x.gear_slot||'',qty:1,effect:x.mechanics?.notes||'',sourceAuthority:x.source_authority});await saveC(c,`${c.name} received item: ${x.name}.`)});
 document.querySelector('#saveNpc')?.addEventListener('click',()=>{const name=document.querySelector('#npcName').value.trim();if(!name)return alert('NPC name required.');const x={schema_version:'1.0',content_type:'npc',id:id('npc'),name,npc_type:document.querySelector('#npcType').value,floor:Number(document.querySelector('#npcFloor').value||1),status:document.querySelector('#npcStatus').value,location:document.querySelector('#npcLocation').value.trim(),faction:document.querySelector('#npcFaction').value.trim(),personality:document.querySelector('#npcPersonality').value.trim(),secrets:document.querySelector('#npcSecrets').value.trim().split('\n').filter(Boolean),source_authority:'THE_DESCENT',gm_approval_required:false};const lib=library();lib.push(x);saveLibrary(lib);feed(`Content Library saved NPC: ${name}.`);render()});
 function hint(){const p=Number(document.querySelector('#encParty')?.value||0),band=document.querySelector('#encPower')?.value,el=document.querySelector('#powerHint');if(!el)return;el.innerHTML=POWER[p]?`RAW starting point for <b>${p}</b> crawlers at <b>${band}</b>: <b>${POWER[p][band]} Mobs</b>. This is guidance, not an automatic difficulty guarantee.`:'RAW Adversary Power reference covers party sizes 2–7.'}
 document.querySelector('#encParty')?.addEventListener('input',hint);document.querySelector('#encPower')?.addEventListener('change',hint);hint();
 document.querySelector('#saveAdversary')?.addEventListener('click',()=>{const name=document.querySelector('#advName').value.trim();if(!name)return alert('Adversary name required.');const src=document.querySelector('#advSource').value,effect=document.querySelector('#advAtkEffect').value.trim(),notes=document.querySelector('#advNotes').value.trim();const x={schema_version:'1.0',content_type:'adversary',id:id('adv'),name,species_type:document.querySelector('#advSpecies').value.trim()||null,classification:document.querySelector('#advClass').value,size:{name:document.querySelector('#advSize').value.trim()||'Medium',value:1},health_bar:{slots:Math.max(1,Number(document.querySelector('#advHealth').value||10))},level:Math.max(1,Number(document.querySelector('#advLevel').value||1)),surprise:document.querySelector('#advSurprise').value.trim()||'11+F',evade:document.querySelector('#advEvade').value.trim()||'11+F',move:document.querySelector('#advMove').value.trim()||'20+S',dr:Math.max(0,Number(document.querySelector('#advDR').value||0)),stats:Object.fromEntries(['STR','INT','CON','DEX','CHA'].map(s=>[s,Math.max(1,Number(document.querySelector('#adv'+s).value||1))])),attacks:[{name:document.querySelector('#advAtkName').value.trim()||'Attack',to_hit:document.querySelector('#advAtkHit').value.trim()||'11+F',damage:document.querySelector('#advAtkDamage').value.trim().toUpperCase()||'1D6',damage_type:document.querySelector('#advAtkType').value.trim()||'Physical',range:document.querySelector('#advAtkRange').value.trim()||'Melee',other_effects:effect?[{text:effect}]:[]}],special_rules:notes?[{text:notes}]:[],notes:[],ai_announcement:document.querySelector('#advAnnouncement').value.trim()||null,source_authority:src,gm_approval_required:['AI_GENERATED','HOMEBREW'].includes(src)};const lib=library();lib.push(x);saveLibrary(lib);feed(`Content Library saved adversary: ${name}.`);render()});
 document.querySelector('#advSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#advList [data-search]').forEach(r=>r.classList.toggle('hidden',!r.dataset.search.includes(q)))});
 document.querySelectorAll('[data-addadv]').forEach(b=>b.onclick=()=>{const x=library().find(z=>z.id===b.dataset.addadv);if(!x)return;workspace='encounters';render();const sel=document.querySelector('#encSavedAdv');if(sel){sel.value=x.id;document.querySelector('#encMobName').value=x.name;document.querySelector('#encMobHealth').value=x.health_bar?.slots||10;document.querySelector('#encMobEvade').value=x.evade||'11+F';document.querySelector('#encMobDr').value=x.dr||0;document.querySelector('#encMobAttack').value=x.attacks?.[0]?.name||'Attack';document.querySelector('#encMobDamage').value=x.attacks?.[0]?.damage||'1D6';}});
 document.querySelector('#saveEncounter')?.addEventListener('click',()=>{const name=document.querySelector('#encName').value.trim();if(!name)return alert('Encounter name required.');const x={schema_version:'1.0',content_type:'encounter',id:id('enc'),name,encounter_type:document.querySelector('#encType').value,floor:Number(document.querySelector('#encFloor').value||1),power_band:document.querySelector('#encPower').value,party_size_reference:Number(document.querySelector('#encParty').value||state.crawlers.length),participants:[(()=>{const aid=document.querySelector('#encSavedAdv').value,a=library().find(z=>z.id===aid);return a?{kind:'adversary',definition_id:a.id,count:Number(document.querySelector('#encCount').value||0),role:'adversaries',template:{name:a.name,health_slots:Number(a.health_bar?.slots||10),evade:a.evade,dr:Number(a.dr||0),surprise:a.surprise,move:a.move,level:a.level,classification:a.classification,stats:a.stats,attacks:a.attacks||[],special_rules:a.special_rules||[]}}:{kind:'dynamic',definition_id:null,count:Number(document.querySelector('#encCount').value||0),role:'adversaries',template:{name:document.querySelector('#encMobName').value.trim()||'Dungeon Mob',health_slots:Math.max(1,Number(document.querySelector('#encMobHealth').value||10)),evade:document.querySelector('#encMobEvade').value.trim()||'11+F',dr:Math.max(0,Number(document.querySelector('#encMobDr').value||0)),attacks:[{name:document.querySelector('#encMobAttack').value.trim()||'Attack',to_hit:'11+F',damage:document.querySelector('#encMobDamage').value.trim().toUpperCase()||'1D6',damage_type:'Physical',range:'Melee'}]}}})()],system_announcement:document.querySelector('#encAnnouncement').value.trim(),objectives:document.querySelector('#encObjectives').value.split('\n').filter(Boolean).map((t,i)=>({id:'obj_'+(i+1),text:t,required:true,hidden:false})),environment:{special_rules:document.querySelector('#encNotes').value.trim()?[{text:document.querySelector('#encNotes').value.trim()}]:[]},source_authority:'THE_DESCENT',gm_approval_required:false};const lib=library();lib.push(x);saveLibrary(lib);feed(`Content Library saved encounter: ${name}.`);render()});
 document.querySelectorAll('[data-deployenc]').forEach(b=>b.onclick=()=>{const x=library().find(z=>z.id===b.dataset.deployenc);if(!x)return;if(active()&&!confirm('Replace the currently active encounter?'))return;const crawlers=state.crawlers.map(c=>({participant_id:'crawler_'+c.id,kind:'crawler',crawler_id:c.id,name:c.name,health:{slots_max:10,slots_current:c.healthSlotsRemaining},conditions:[]}));const adversaries=[];(x.participants||[]).filter(p=>p.role==='adversaries').forEach(p=>{for(let i=0;i<Number(p.count||0);i++){const t=p.template||{};adversaries.push({participant_id:id('mob'),kind:'adversary',name:`${t.name||'Dungeon Mob'} ${i+1}`,health:{slots_max:Number(t.health_slots||10),slots_current:Number(t.health_slots||10)},dr:Number(t.dr||0),evade:t.evade||'11+F',surprise:t.surprise||'—',move:t.move||'—',level:t.level||x.floor,classification:t.classification||'Mob',stats:t.stats||{},attacks:t.attacks||[],special_rules:t.special_rules||[],conditions:[]})}});const runtime={instance_id:id('active'),definition_id:x.id,name:x.name,status:'active',round:1,phase:'mobs',floor:x.floor,party_size:state.crawlers.length,participants:[...crawlers,...adversaries],actions_remaining:Object.fromEntries(state.crawlers.map(c=>[c.id,2])),objective_state:Object.fromEntries((x.objectives||[]).map(o=>[o.id,'active'])),event_log:[],started_at:new Date().toISOString()};saveActive(runtime);feed(`Encounter deployed: ${x.name}. Round 1 begins with the Mob phase unless crawlers achieved surprise.`);render()});
 document.querySelectorAll('[data-deletecontent]').forEach(b=>b.onclick=()=>{const lib=library(),x=lib.find(z=>z.id===b.dataset.deletecontent);if(x&&confirm(`Delete ${x.name} from local Content Library?`)){saveLibrary(lib.filter(z=>z.id!==x.id));render()}});
 document.querySelectorAll('[data-die]').forEach(b=>b.onclick=()=>{const d=Number(b.dataset.die),r=Math.floor(Math.random()*d)+1;document.querySelector('#tableRoll').textContent=`d${d} → ${r}`});
}
document.querySelector('#workspaceNav').onclick=e=>{const b=e.target.closest('[data-workspace]');if(b){workspace=b.dataset.workspace;render()}};
window.addEventListener('descent-crawler-update',e=>{const i=state.crawlers.findIndex(c=>String(c.id)===String(e.detail.id));if(i>=0){const msgs=state.crawlers[i].messages||[];state.crawlers[i]=e.detail.data;state.crawlers[i].messages=msgs}else state.crawlers.push(e.detail.data);render()});
window.addEventListener('descent-feed-update',()=>{const s=readState();if(s?.feed)state.feed=s.feed;render()});
window.addEventListener('descent-message-update',()=>{const s=readState();if(s?.crawlers)state.crawlers=s.crawlers;render()});
await initContentCloud();setInterval(header,30000);render();
})().catch(e=>document.querySelector('#workspace').innerHTML=`<div class="notice">${esc(e.message)}</div>`);